import palmImg from "@/assets/palm-jumeirah.jpg";
import penthouseImg from "@/assets/penthouse-interior.jpg";
import heroImg from "@/assets/hero-dubai.jpg";
import interiorImg from "@/assets/interior-luxury.jpg";

export interface Property {
  id: number;
  image: string;
  images: string[];
  title: string;
  location: string;
  beds: number;
  baths: number;
  area: string;
  areaSqft: number;
  price: string;
  priceNum: number;
  action: string;
  status: string;
  type: string;
  category: string;
  developer: string;
  towerName: string;
  refNo: string;
  description: string;
}

export const allProperties: Property[] = [
  {
    id: 1,
    image: palmImg,
    images: [palmImg, penthouseImg, heroImg, interiorImg],
    title: "Palm Paying | Great for Investment | Flexible Payment Plan",
    location: "Palm Jumeirah",
    beds: 5,
    baths: 6,
    area: "12,500",
    areaSqft: 12500,
    price: "AED 4,410,000",
    priceNum: 4410000,
    action: "Buy",
    status: "Completed",
    type: "Villas",
    category: "Residential",
    developer: "Nakheel",
    towerName: "Palm Residences",
    refNo: "GC-PR-1001",
    description: "A stunning 5-bedroom villa located in the iconic Palm Jumeirah. This property offers breathtaking sea views, a private pool, and direct beach access. The villa features premium finishes, spacious living areas, and a modern kitchen equipped with top-of-the-line appliances.",
  },
  {
    id: 2,
    image: penthouseImg,
    images: [penthouseImg, palmImg, heroImg, interiorImg],
    title: "Flexible Payment Plan | Breathtaking View from Every Angle",
    location: "Downtown Dubai",
    beds: 4,
    baths: 5,
    area: "8,200",
    areaSqft: 8200,
    price: "AED 6,800,000",
    priceNum: 6800000,
    action: "Buy",
    status: "Completed",
    type: "Penthouses",
    category: "Residential",
    developer: "Emaar",
    towerName: "Burj Royale",
    refNo: "GC-BR-2002",
    description: "An exceptional penthouse in the heart of Downtown Dubai offering panoramic views of the Burj Khalifa and Dubai Fountain. This luxurious residence features floor-to-ceiling windows, a private terrace, and world-class amenities including a rooftop infinity pool.",
  },
  {
    id: 3,
    image: heroImg,
    images: [heroImg, palmImg, penthouseImg, interiorImg],
    title: "Exclusive Residential | Skyline by Address Hotels",
    location: "Dubai Marina",
    beds: 3,
    baths: 4,
    area: "4,800",
    areaSqft: 4800,
    price: "AED 5,899,898",
    priceNum: 5899898,
    action: "Buy",
    status: "Completed",
    type: "Apartments",
    category: "Residential",
    developer: "Emaar",
    towerName: "Address Marina",
    refNo: "GC-AM-3003",
    description: "A premium 3-bedroom apartment in the prestigious Address Marina tower. Enjoy resort-style living with access to a private beach, world-class spa, and fine dining. The apartment features a modern open-plan layout with premium marble finishes throughout.",
  },
  {
    id: 4,
    image: interiorImg,
    images: [interiorImg, heroImg, palmImg, penthouseImg],
    title: "Luxurious Apartment | Breathtaking Rise Residences",
    location: "Dubai Harbour",
    beds: 3,
    baths: 3,
    area: "3,200",
    areaSqft: 3200,
    price: "AED 16,000,000",
    priceNum: 16000000,
    action: "Buy",
    status: "Completed",
    type: "Apartments",
    category: "Residential",
    developer: "Sobha",
    towerName: "Rise Residences",
    refNo: "GC-RR-4004",
    description: "An ultra-luxury apartment in the exclusive Dubai Harbour development. This property offers stunning views of the Arabian Gulf and Palm Jumeirah. Features include a private elevator, smart home automation, and access to a yacht club and marina.",
  },
  {
    id: 5,
    image: palmImg,
    images: [palmImg, interiorImg, heroImg, penthouseImg],
    title: "Ideal for Investment | Skyview | Penthouse",
    location: "Dubai Harbour",
    beds: 4,
    baths: 5,
    area: "6,500",
    areaSqft: 6500,
    price: "AED 28,000,000",
    priceNum: 28000000,
    action: "Buy",
    status: "Completed",
    type: "Penthouses",
    category: "Residential",
    developer: "Meraas",
    towerName: "Skyview Tower",
    refNo: "GC-ST-5005",
    description: "A trophy penthouse in the iconic Skyview Tower at Dubai Harbour. This extraordinary residence spans the top floor with 360-degree views of the Dubai skyline. Features include a private rooftop terrace, plunge pool, and dedicated concierge service.",
  },
  {
    id: 6,
    image: penthouseImg,
    images: [penthouseImg, palmImg, heroImg, interiorImg],
    title: "Flexible Payment Plan – Great for Investment",
    location: "Dubai Harbour",
    beds: 2,
    baths: 3,
    area: "2,100",
    areaSqft: 2100,
    price: "AED 16,700,000",
    priceNum: 16700000,
    action: "Buy",
    status: "Off Plan",
    type: "Apartments",
    category: "Residential",
    developer: "Sobha",
    towerName: "Harbour Gate",
    refNo: "GC-HG-6006",
    description: "A stunning off-plan apartment in the upcoming Harbour Gate development. This property offers flexible payment plans and is ideal for investors looking for high returns. Features include a modern design, premium finishes, and access to world-class amenities.",
  },
  {
    id: 7,
    image: heroImg,
    images: [heroImg, interiorImg, palmImg, penthouseImg],
    title: "3 Bedroom Extended Brand New Villa for Rent – Fully Furnished",
    location: "DAMAC Hills 2 (Akoya by DAMAC)",
    beds: 3,
    baths: 3,
    area: "1,802",
    areaSqft: 1802,
    price: "AED 95,000",
    priceNum: 95000,
    action: "Rent",
    status: "Completed",
    type: "Villas",
    category: "Residential",
    developer: "DAMAC",
    towerName: "Amargo",
    refNo: "3755-Th-R-1058",
    description: "Fully Furnished | Sunset View | Spacious Layout\n\nDAMAC Hills 2 is a master community that curates a one-of-a-kind living experience inspired by water, sports and fun for all ages. Previously known as AKOYA, DAMAC Hills 2 features clusters of thoughtfully designed apartments, townhouses and villas surrounded by a whole new range of experiences, attractions, convenience.",
  },
  {
    id: 8,
    image: interiorImg,
    images: [interiorImg, heroImg, palmImg, penthouseImg],
    title: "3 Bedroom Corner Unit First Rate Good Investment",
    location: "DAMAC Hills 2 (Akoya by DAMAC)",
    beds: 3,
    baths: 3,
    area: "2,200",
    areaSqft: 2200,
    price: "AED 1,800,000",
    priceNum: 1800000,
    action: "Buy",
    status: "Completed",
    type: "Townhouses",
    category: "Residential",
    developer: "DAMAC",
    towerName: "Claret",
    refNo: "GC-CL-8008",
    description: "A spacious 3-bedroom corner townhouse in the sought-after DAMAC Hills 2 community. This property features a private garden, covered parking, and access to community amenities including a swimming pool, gym, and children's play area.",
  },
  {
    id: 9,
    image: palmImg,
    images: [palmImg, interiorImg, heroImg, penthouseImg],
    title: "KEY EXPENSES READY TO MOVE IN | 2 BR Apartment",
    location: "Jumeirah Village Circle (JVC)",
    beds: 2,
    baths: 2,
    area: "1,200",
    areaSqft: 1200,
    price: "AED 110,000",
    priceNum: 110000,
    action: "Rent",
    status: "Completed",
    type: "Apartments",
    category: "Residential",
    developer: "Nakheel",
    towerName: "Circle Mall Residences",
    refNo: "GC-CM-9009",
    description: "A well-maintained 2-bedroom apartment in Jumeirah Village Circle, one of Dubai's most popular residential communities. The apartment is ready to move in and comes with all key expenses included. Close to schools, shopping, and public transport.",
  },
  {
    id: 10,
    image: penthouseImg,
    images: [penthouseImg, palmImg, heroImg, interiorImg],
    title: "Good For Investment | Flexible Payment Plan",
    location: "The Valley",
    beds: 4,
    baths: 4,
    area: "3,600",
    areaSqft: 3600,
    price: "AED 3,310,000",
    priceNum: 3310000,
    action: "Buy",
    status: "Off Plan",
    type: "Townhouses",
    category: "Residential",
    developer: "Emaar",
    towerName: "Eden",
    refNo: "GC-ED-1010",
    description: "A modern 4-bedroom townhouse in Emaar's The Valley community. This off-plan property offers a flexible payment plan and is set within lush green landscapes. Features include a private garden, rooftop terrace, and access to a clubhouse, sports facilities, and retail outlets.",
  },
  {
    id: 11,
    image: heroImg,
    images: [heroImg, palmImg, penthouseImg, interiorImg],
    title: "FLEXIBLE PAYMENT PLAN | NEW LAUNCH",
    location: "The Valley",
    beds: 3,
    baths: 3,
    area: "2,400",
    areaSqft: 2400,
    price: "AED 5,610,000",
    priceNum: 5610000,
    action: "Sale",
    status: "Off Plan",
    type: "Villas",
    category: "Residential",
    developer: "Emaar",
    towerName: "Alana",
    refNo: "GC-AL-1111",
    description: "A brand new 3-bedroom villa in Emaar's latest launch at The Valley. This off-plan property features a contemporary design, spacious interiors, and a private garden. The community offers a range of amenities including parks, schools, and retail outlets.",
  },
  {
    id: 12,
    image: interiorImg,
    images: [interiorImg, penthouseImg, palmImg, heroImg],
    title: "Premium Residence | Sea View | Modern Design",
    location: "JBR, Dubai",
    beds: 2,
    baths: 2,
    area: "1,800",
    areaSqft: 1800,
    price: "AED 1,448,888",
    priceNum: 1448888,
    action: "Buy",
    status: "Completed",
    type: "Apartments",
    category: "Residential",
    developer: "Meraas",
    towerName: "Bluewaters Residences",
    refNo: "GC-BW-1212",
    description: "A premium 2-bedroom apartment with stunning sea views in JBR. This modern residence features high-end finishes, an open-plan living area, and a spacious balcony. Access to the beach, dining, and entertainment is just steps away.",
  },
  {
    id: 13,
    image: palmImg,
    images: [palmImg, heroImg, penthouseImg, interiorImg],
    title: "Prime Commercial Office | Business Bay",
    location: "Business Bay",
    beds: 0,
    baths: 2,
    area: "2,500",
    areaSqft: 2500,
    price: "AED 2,200,000",
    priceNum: 2200000,
    action: "Buy",
    status: "Completed",
    type: "Offices",
    category: "Commercial",
    developer: "DAMAC",
    towerName: "DAMAC Business Tower",
    refNo: "GC-BT-1313",
    description: "A prime commercial office space in the heart of Business Bay. This fully fitted office features modern interiors, high-speed connectivity, and stunning views of the Dubai Canal. Ideal for businesses looking for a prestigious address.",
  },
  {
    id: 14,
    image: heroImg,
    images: [heroImg, palmImg, interiorImg, penthouseImg],
    title: "Retail Space | High Footfall Area | Ground Floor",
    location: "Dubai Marina",
    beds: 0,
    baths: 1,
    area: "1,500",
    areaSqft: 1500,
    price: "AED 3,500,000",
    priceNum: 3500000,
    action: "Sale",
    status: "Completed",
    type: "Retail",
    category: "Commercial",
    developer: "Emaar",
    towerName: "Marina Walk",
    refNo: "GC-MW-1414",
    description: "A premium retail space on the ground floor of Marina Walk, one of Dubai's busiest pedestrian areas. This shop features double-height ceilings, large display windows, and excellent visibility. Perfect for F&B, fashion, or lifestyle brands.",
  },
  {
    id: 15,
    image: penthouseImg,
    images: [penthouseImg, heroImg, palmImg, interiorImg],
    title: "Prime Residential Plot | Gated Community",
    location: "Dubai Hills Estate",
    beds: 0,
    baths: 0,
    area: "15,000",
    areaSqft: 15000,
    price: "AED 12,500,000",
    priceNum: 12500000,
    action: "Buy",
    status: "Completed",
    type: "Plots",
    category: "Residential",
    developer: "Emaar",
    towerName: "Dubai Hills",
    refNo: "GC-DH-1515",
    description: "A premium residential plot in the exclusive Dubai Hills Estate gated community. Build your dream villa on this expansive plot with views of the championship golf course. The community offers world-class amenities including parks, schools, and a luxury mall.",
  },
];

export const ITEMS_PER_PAGE = 9;
